### ISSUE TITLE
Cannot run gradle startDockerEnv

### ISSUE THREAD

**Issue by mouzofabricio** [GlassOfWhiskey/docker-liferay-workspace-example#1]
Hi!
I;m having problems while trying to run the gradle startDockerEnv 
All the tasks run fine but when I see the logs on the portal container I get this : 
```
oading jar:file:/usr/local/liferay-ce-portal-7.0-ga5/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
Loading jar:file:/usr/local/liferay-ce-portal-7.0-ga5/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/portal.properties
Loading file:/usr/local/liferay-ce-portal-7.0-ga5/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/portal-docker.properties
03:28:24,932 INFO  [localhost-startStop-1][HikariDataSource:95] HikariPool-1 - Starting...
03:28:25,417 INFO  [localhost-startStop-1][PoolBase:491] HikariPool-1 - Driver does not support get/set network timeout for connections. (feature not supported)
03:28:25,422 INFO  [localhost-startStop-1][HikariDataSource:107] HikariPool-1 - Start completed.
03:28:25,433 INFO  [localhost-startStop-1][DialectDetector:77] Determine dialect for HSQL Database Engine 2.3
03:28:25,531 WARN  [localhost-startStop-1][DialectDetector:95] Liferay is configured to use Hypersonic as its database. Do NOT use Hypersonic in production. Hypersonic is an embedded database useful for development and demonstration purposes. The database settings can be changed in portal-ext.properties.
03:28:25,537 INFO  [localhost-startStop-1][DialectDetector:153] Found dialect com.liferay.portal.dao.orm.hibernate.HSQLDialect
03:28:27,321 INFO  [localhost-startStop-1][HikariDataSource:95] HikariPool-2 - Starting...
03:28:27,323 INFO  [localhost-startStop-1][PoolBase:491] HikariPool-2 - Driver does not support get/set network timeout for connections. (feature not supported)
03:28:27,324 INFO  [localhost-startStop-1][HikariDataSource:107] HikariPool-2 - Start completed.
03:28:27,799 INFO  [localhost-startStop-1][BundleStartStopLogger:35] STARTED org.eclipse.osgi_3.10.200.v20150831-0856 [0]
03:28:27,902 ERROR [Framework Event Dispatcher: Equinox Container: 50a5059f-f18e-0018-1fc7-b9fb9ddb05f3][com_liferay_portal_startup_monitor:97] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.startup.monitor [1]_  Unresolved requirement: Import-Package: org.osgi.service.component; version="[1.3.0,2.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:429)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
03:28:27,929 ERROR [Framework Event Dispatcher: Equinox Container: 50a5059f-f18e-0018-1fc7-b9fb9ddb05f3][com_liferay_util_taglib:97] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: com.liferay.util.taglib [3]_  Unresolved requirement: Import-Package: javax.el_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:429)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

Any Idea what could be the issue ? I've run other Liferay container without any problems but I think you startup project would be super nice to bootstrap a new project I;m working on. 

Thanks in advance.

**Comment by GlassOfWhiskey** [comment]
Hi,
you have to launch gradle initBundle task before startDockerEnv, in order to properly initialize Liferay environment and correctly resolve volume bindings inside docker-compose file

**Comment by mouzofabricio** [comment]
Hi man,
Thanks a lot for your help. The initBundle task was the issue. 

After solving that I found another problem while trying to run the gulp watch task. 

I made the proper configuration in a liferay-theme generated with yeoman. I changed the liferay-theme.json to point to the proper build folders. This is the message I get which shows no errors but for some reason the theme never shows at my liferay container :s.  

```
07:28:19,787 INFO  [Thread-57][BaseAutoDeployListener:50] Themes for /tmp/themes/test-theme/.web_bundle_build copied successfully
07:28:20,956 INFO  [Thread-57][HotDeployImpl:226] Deploying test-theme from queue
07:28:20,956 INFO  [Thread-57][PluginPackageUtil:1007] Reading plugin package for test-theme
25-Jul-2018 07:28:21.087 INFO [Thread-57] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
07:28:21,096 INFO  [Thread-57][ThemeHotDeployListener:94] Registering themes for test-theme
07:28:21,443 INFO  [Thread-57][ThemeHotDeployListener:109] 1 theme for test-theme is available for use
07:28:21,597 INFO  [Thread-57][BundleStartStopLogger:35] STARTED test-theme_1.0.0 [517]
```

This is my liferay-theme.json

```
{
  "LiferayTheme": {
    "deployPath": "/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/bundles/deploy",
    "themeName": "test-theme",
    "appServerPathTheme": "/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/bundles/tomcat-8.0.32/webapps",
    "appServerPath": "/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/bundles/tomcat-8.0.32",
    "deployed": true,
    "appServerPathPlugin": "/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/.web_bundle_build",
    "webBundleDir": "watching"
  }
}
```

**Comment by mouzofabricio** [comment]
Hi, I was able to make it work. Using the master branch as a starting point. 

The problem I have right now is while trying to use gulp watch and modifying the css. 
```
docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/docker-gulp-tasks-4-liferay/node_modules/run-sequence/index.js:20
			throw new Error("Task "+t+" is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).");
			^

Error: Task build:prep-css is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at /Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/docker-gulp-tasks-4-liferay/node_modules/run-sequence/index.js:20:10
    at Array.forEach (<anonymous>:null:null)
    at verifyTaskSets (/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/docker-gulp-tasks-4-liferay/node_modules/run-sequence/index.js:13:11)
    at runSequence (/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/docker-gulp-tasks-4-liferay/node_modules/run-sequence/index.js:92:2)
    at /Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/docker-gulp-tasks-4-liferay/tasks/docker_watch.js:146:16
    at Gaze.<anonymous> (/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/glob-watcher/index.js:18:14)
    at emitTwo (events.js:126:13)
    at Gaze.emit (events.js:214:7)
    at Gaze.emit (/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/gaze/lib/gaze.js:129:32)
    at /Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/gaze/lib/gaze.js:415:16
    at StatWatcher._pollers.(anonymous function) (/Users/fbrmz/docker-liferay/docker-liferay-workspace-example/themes/test-theme/node_modules/gaze/lib/gaze.js:326:7)
    at emitTwo (events.js:126:13)
    at StatWatcher.emit (events.js:214:7)
    at StatWatcher._handle.onchange (fs.js:1452:10)
```

Also when I create a site template in order to create web-content structures/templates they do not update properly on the liferay instance. Is there a way to solve this ? 

Thanks in advance. The video and blog post was super helpful 👍 

PS: Im workign on MacOSX

**Comment by GlassOfWhiskey** [comment]
Hi,
I'm happy it worked for you ^_^.
Concerning the gulp related tasks, please refer to the dedicated git repo
https://github.com/GlassOfWhiskey/docker-gulp-tasks-4-liferay
In particular, for the problem you report there is an issue open that asks for Liferay 7.1 support:
https://github.com/GlassOfWhiskey/docker-gulp-tasks-4-liferay/issues/2
